name: flutter_getx_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  dio: ^4.0.0
  json_annotation: ^4.0.1
  intl: ^0.17.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_flavorizr: ^2.0.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  mockito: ^5.0.9
  http_mock_adapter: ^0.2.1
  faker: ^2.0.0

flutter: 
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "SecretWall dev"

      android:
        applicationId: "com.example.flutter_getx_template.dev"

      ios:
        bundleId: "com.example.flutter_getx_template.dev"

    qa:
      app:
        name: "SecretWall qa"

      android:
        applicationId: "com.example.flutter_getx_template.qa"
      ios:
        bundleId: "com.example.flutter_getx_template.qa"

    prod:
      app:
        name: "SecretWall"

      android:
        applicationId: "com.example.flutter_getx_template"
      ios:
        bundleId: "com.example.flutter_getx_template"